version: '3.8'
services:
  postgres-product:
    container_name: postgres-product
    image: postgres
    environment:
      POSTGRES_DB: product-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tranthanhtan
      PGDATA: /data/postgres
    volumes:
      - D:/Hoc tap/Thuc tap/Do an/Database/postgres-product:/data/postgres
    ports:
      - "5431:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres-order:
    container_name: postgres-order
    image: postgres
    environment:
      POSTGRES_DB: order-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tranthanhtan
      PGDATA: /data/postgres
    volumes:
      - D:/Hoc tap/Thuc tap/Do an/Database/postgres-order:/data/postgres
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres-inventory:
    container_name: postgres-inventory
    image: postgres
    environment:
      POSTGRES_DB: inventory-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tranthanhtan
      PGDATA: /data/postgres
    volumes:
      - D:/Hoc tap/Thuc tap/Do an/Database/postgres-inventory:/data/postgres
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres-customer:
    container_name: postgres-customer
    image: postgres
    environment:
      POSTGRES_DB: customer-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tranthanhtan
      PGDATA: /data/postgres
    volumes:
      - D:/Hoc tap/Thuc tap/Do an/Database/postgres-customer:/data/postgres
    ports:
      - "5434:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  discovery-server:
    image: thanhtantg2003/discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    depends_on:
      - jaeger
    env_file:
      - variables.env
    environment:
      - EUREKA_INSTANCE_HOSTNAME=discovery-server
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOST}:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  product-service:
    container_name: product-service
    image: thanhtantg2003/product-service:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-product:5432/product-service
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://${HOST}:5432/product-service
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - OTEL_SERVICE_NAME=product-service
      - OTEL_METRICS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250
    env_file:
      - variables.env
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server
      - api-gateway
      - jaeger
      - postgres-product
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://${HOST}:8082/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5


  order-service:
    container_name: order-service
    image: thanhtantg2003/order-service:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-order:5432/order-service
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://${HOST}:5432/order-service
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    env_file:
      - variables.env
    ports:
      - "8082:8082"
    depends_on:
      - discovery-server
      - api-gateway
      - jaeger
      - postgres-order
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOST}:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  inventory-service:
    container_name: inventory-service
    image: thanhtantg2003/inventory-service:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-inventory:5432/inventory-service
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://${HOST}:5432/inventory-service
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    env_file:
      - variables.env
    ports:
      - "8083:8083"
    depends_on:
      - discovery-server
      - api-gateway
      - jaeger
      - postgres-inventory
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOST}:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  customer-service:
    container_name: customer-service
    image: thanhtantg2003/customer-service:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-customer:5432/customer-service
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://${HOST}:5432/customer-service
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    env_file:
      - variables.env
    ports:
      - "8084:8084"
    depends_on:
      - discovery-server
      - api-gateway
      - jaeger
      - postgres-customer
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOST}:8084/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  api-gateway:
    image: thanhtantg2003/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    env_file:
      - variables.env
    depends_on:
      - discovery-server
      - jaeger
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOST}:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250:14250"